apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sglang-model.fullname" . }}
spec:
  accessModes:
{{ toYaml .Values.pvc.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
{{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
{{- end }}